---
- name: FMC REST API
  hosts: localhost
  vars_files:
    - vars.yml
    - credentials.yaml
  tasks:
    - name: Get Access Token
      uri:
        url: https://{{ ansible_host  }}/{{ auth_path }}
        method: POST
        headers:
          Content-Type: "application/json"
          Connection: "keep-alive"
        validate_certs: no
        user: "{{fmc_username}}"
        password: "{{fmc_password}}"
        force: yes
        force_basic_auth: yes
        status_code: 204
        return_content: yes
      register: auth
    - name: get token
      set_fact:
        auth_token: "{{auth.x_auth_access_token}}"
    - name: GET Access Policy
      uri:
        url: "https://{{ ansible_host  }}/{{ resource_path }}/{{ auth.domain_uuid}}/policy/accesspolicies?name=CLUS2022"
        method: GET
        headers:
          "x-auth-access-token": "{{auth_token}}"
          Connection: keep-alive
        validate_certs: no
        status_code: [200,400,404]
        body_format: json
      register: getaccesspolicies
      ignore_errors: yes
    - name: Get Inside Security Zone
      uri:
        url: "https://{{ ansible_host  }}/{{ resource_path }}/{{ auth.domain_uuid}}/object/securityzones?name=INSIDE"
        method: GET
        validate_certs: no
        headers:
          "x-auth-access-token": "{{auth_token}}"
          Connection: keep-alive
        body_format: json
        status_code: [200]
      register: inseczone
    - name: Get  OUTSIDE Security Zone
      uri:
        url: "https://{{ ansible_host  }}/{{ resource_path }}/{{ auth.domain_uuid}}/object/securityzones?name=OUTSIDE"
        method: GET
        validate_certs: no
        headers:
          "x-auth-access-token": "{{auth_token}}"
          Connection: keep-alive
        body_format: json
        status_code: [200]
      register: outseczone
    - name: Get Policy ID
      set_fact:
        policy_id: "{{item.id}}"
      with_items: "{{getaccesspolicies.json | json_query('items[]') }}"
    - name: Get Inside Zone ID
      set_fact:
        insec: "{{item}}"
      with_items: "{{inseczone.json | json_query('items[]' )}}"
    - name: Get Outside Zone ID
      set_fact:
        outsec: "{{item}}"
      with_items: "{{outseczone.json | json_query('items[]' )}}"
    - name: Create Access Rule
      uri:
        url: "https://{{ ansible_host  }}/{{ resource_path }}/{{ auth.domain_uuid}}/policy/accesspolicies/{{policy_id}}/accessrules"
        method: POST
        validate_certs: no
        headers:
          "x-auth-access-token": "{{auth_token}}"
          Connection: keep-alive
        body_format: json
        status_code: [201]
        body:
          action: "ALLOW"
          enabled: true
          type: "AccessRule"
          name: "CLUS_Test"
          sendEventsToFMC: true
          logEnd: true
          sourceZones:
            objects:
              - name: "{{insec.name}}"
                id: "{{insec.id}}"
                type: "{{insec.type}}"
          destinationZones:
            objects:
              - name: "{{outsec.name}}"
                id: "{{outsec.id}}"
                type: "{{outsec.type}}"
      register: policy
    - name: GET Device Details
      uri:
        url: "https://{{ ansible_host  }}/{{ resource_path }}/{{ auth.domain_uuid}}/devices/devicerecords"
        method: GET
        headers:
          "x-auth-access-token": "{{auth_token}}"
          Connection: keep-alive
        validate_certs: no
        status_code: [200,400]
        body_format: json

      register: getdevice
    - name: Get Deployments
      uri:
        url: "https://{{ ansible_host  }}/{{ resource_path }}/{{ auth.domain_uuid}}/deployment/deployabledevices"
        method: GET
        headers:
          "x-auth-access-token": "{{auth_token}}"
          Connection: keep-alive
        validate_certs: no
        status_code: [200,400]
        body_format: json
      register: deployable
    - name: Get Timestamp
      set_fact:
        stamp: "{{ item.version}}"
      with_list: "{{deployable.json | json_query('items[]')}}"
    - name: Value
      set_fact:
        devicelist: "{{ getdevice.json | json_query('items[*].id' ) | list}}"
    - name: Deploy Changes
      uri:
        url: "https://{{ ansible_host  }}/{{ resource_path }}/{{ auth.domain_uuid}}/deployment/deploymentrequests"
        method: POST
        headers:
          "x-auth-access-token": "{{auth_token}}"
          Connection: keep-alive
        validate_certs: no
        status_code: [202,200]
        body_format: json
        body:
          type: "DeploymentRequest"
          version:  "{{ stamp}}"
          ignoreWarning: true
          deviceList: "{{devicelist}}"
